run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocyclo
    - dupl
    - goconst
    - revive
    - misspell
    - unparam
    - unconvert
    - prealloc
    - exportlooprec
    - nolintlint

linters-settings:
  gosec:
    excludes:
      - G104
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: exported
        severity: warning
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
